# Generated by Django 3.2 on 2021-05-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
    ]
